# -*- coding: utf-8 -*-
"""Book_Recommendation (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqzBvP4kkUtz2HjFf7oGy6-3cZ64QhGf

Importing Dependencies
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""user dataset"""

## Load the users dataset
users=pd.read_csv("Users.csv")

## number of rows and columns in the DataFrame
users.shape

## first 5 rows of DataFrame
users.head()

## getting some informations about the dataset
users.info()

## statistical Measures of the dataset
users.describe()

##check duplicates
users.duplicated().sum()

"""No duplicates present in users dataset"""

##check missing values
users.isnull().sum()

"""Age column contain null value"""

users['Age'] = users['Age'].fillna(users['Age'].median())

users.isnull().sum()

users['Age'] = users['Age'].astype(int)

users.info()

## unique values present in age
users['Age'].unique()

users.loc[(users['Age'] < 5) | (users['Age'] > 90), 'Age'] = users['Age'].median()

users['Age'].unique()

## check outliers
users.boxplot()

def outlier_cappping(df,column):
    Q1= df[column].quantile(0.25)
    Q3= df[column].quantile(0.75)
    IQR= Q3-Q1
    lower_extreme= Q1-1.5*IQR
    upper_extreme= Q3+1.5*IQR
    df[column]=df[column].apply(lambda x: lower_extreme if x<lower_extreme else upper_extreme if x>upper_extreme else x)
for col in users.select_dtypes(['int','float']).columns:
    outlier_cappping(users,col)

users.boxplot()

"""Age Distribution"""

plt.hist(users['Age'],bins=30)
plt.title("Distribution of user age")
plt.xlabel("Age")
plt.ylabel("Number of Users")
plt.show()

"""From this graph we can say that most users are between 30-35 age group

rating dataset
"""

## load rating dataset
ratings = pd.read_csv("Ratings.csv")

## number of rows and columns in the DataFrame
ratings.shape

## frist 5 rows of DataFrame
ratings.head()

## some information about the DataFeame
ratings.info()

## check duplicates
ratings.duplicated().sum()

"""No duplicate values present in ratings dataset"""

## check null values
ratings.isnull().sum()

"""There is no  null value in rating dataset"""

## chech outliers
ratings.boxplot()

"""No outliers present"""

## unique values present in ratings dataset
ratings['Book-Rating'].unique()

## Rating Distribution
rating_counts = ratings['Book-Rating'].value_counts().sort_index()
rating_counts

## Bar plot
plt.bar(rating_counts.index, rating_counts.values)
plt.xlabel("Rating")
plt.ylabel("Number of Ratings")
plt.title("Distribution of Book Ratings")
plt.show()

"""Books dataset"""

## load the books dataset
books=pd.read_csv("Books.csv")

## number of rows and columns in the DataFrame
books.shape

## first 5 rows in the DataFrame
books.head()

## some information about the dataset
books.info()

## check duplicates
books.duplicated().sum()

"""No duplicate value present in books dataset"""

## check null values
books.isnull().sum()

books['Book-Author']=books['Book-Author'].fillna("unknown")

books['Publisher']=books['Publisher'].fillna("unknown")

books['Image-URL-L']=books['Image-URL-L'].fillna("Image-URL-M")

books.isnull().sum()

books['Year-Of-Publication'].unique()

"""As you can see in Year-of-Publication columns some strings are present. so we have to convert that into integer form"""

books['Year-Of-Publication'] = pd.to_numeric(books['Year-Of-Publication'], errors='coerce')

books['Year-Of-Publication'].fillna(books['Year-Of-Publication'].median(), inplace=True)

books['Year-Of-Publication'] = books['Year-Of-Publication'].astype(int)

books.info()

# Count books per year
books_per_year = books['Year-Of-Publication'].value_counts().sort_index()
books_per_year

# Remove unrealistic years
books = books[(books['Year-Of-Publication'] > 1900) &
              (books['Year-Of-Publication'] <= 2025)]

books_per_year = books['Year-Of-Publication'].value_counts().sort_index()
books_per_year

plt.figure()
plt.plot(books_per_year.index, books_per_year.values)
plt.xlabel("Year")
plt.ylabel("Number of Books Published")
plt.title("Books Published Per Year")
plt.show()

"""Merge the DataSets"""

ratings_users=pd.merge(ratings,users,on='User-ID',how='inner')
ratings_users

final_df=pd.merge(ratings_users,books,on='ISBN',how='inner')
final_df

final_df.shape

## Top rated books
final_df.groupby('Book-Title')['Book-Rating'].mean().sort_values(ascending=False).head(10)

## Average rating per book
book_avg_rating = ratings.groupby('ISBN')['Book-Rating'].mean().reset_index()
book_avg_rating.rename(columns={'Book-Rating':'Avg_Rating'}, inplace=True)

final_df = final_df.merge(book_avg_rating, on='ISBN')

final_df

## top publishers with highesst rating
final_df.groupby('Publisher')['Book-Rating'].mean().sort_values(ascending=False).head(10).plot(kind='bar')

#Year of Publication vs Rating
sns.scatterplot(x='Year-Of-Publication', y='Book-Rating', data=final_df)

"""There is no clear correlation between publication year and rating, indicating that both old and new books receive comparable user appreciation"""

## Correlation Analysis
final_df[['Age','Book-Rating','Year-Of-Publication']].corr()

sns.heatmap(final_df[['Age','Book-Rating','Year-Of-Publication']].corr(),annot=True)

"""Weak correlation between age and rating indicates that rating preference is not strongly age dependent"""

# keeping only explicit ratings
final_df = final_df[final_df['Book-Rating'] > 0]
print("Explict Data Shape: ", final_df.shape)

final_df

# keeping only explicit ratings
final_df = final_df[final_df['Book-Rating'] > 0]
print("Explict Data Shape: ", final_df.shape)

user_counts = final_df['User-ID'].value_counts()
active_users = user_counts[user_counts >= 20].index

final_df = final_df[final_df['User-ID'].isin(active_users)]

book_counts = final_df['Book-Title'].value_counts()
popular_books = book_counts[book_counts >= 20].index

final_df = final_df[final_df['Book-Title'].isin(popular_books)]

print("Users:", final_df['User-ID'].nunique())
print("Books:", final_df['Book-Title'].nunique())
print("Total ratings:", final_df.shape)

final_df

user_item_matrix = final_df.pivot_table(
    index='User-ID',
    columns='Book-Title',
    values='Book-Rating'
)
user_item_matrix

user_item_matrix.fillna(0, inplace=True)

print(user_item_matrix.shape)

user_item_matrix

sparsity = 1 - (np.count_nonzero(user_item_matrix) / user_item_matrix.size)
print("Sparsity:", sparsity)

"""**USER-BASED CF**"""

## Normalizing the data
user_item_norm = user_item_matrix.subtract(
    user_item_matrix.mean(axis=1), axis=0
).fillna(0)
user_item_norm

from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(user_item_norm)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)
user_similarity_df

"""1 → Very similar

0 → Not similar
"""

## Recommendation Function
def recommend_user_based(user_id, top_n=5):

    ## top 20 usere most similar to the target user
    similar_users = user_similarity_df[user_id] \
                        .sort_values(ascending=False)[1:21]

    ## extract similar user_id
    similar_users_ids = similar_users.index

    ## get their avg book rating
    recommended_books = user_item_matrix.loc[similar_users_ids] \
                            .mean().sort_values(ascending=False)

    already_read = user_item_matrix.loc[user_id]
    recommended_books = recommended_books[already_read == 0]

    return recommended_books.head(top_n)

recommend_user_based(user_item_matrix.index[0])

"""**ITEM-BASED CF**

"""

item_similarity = cosine_similarity(user_item_matrix.T)

item_similarity_df = pd.DataFrame(
    item_similarity,
    index=user_item_matrix.columns,
    columns=user_item_matrix.columns
)
item_similarity

def recommend_item_based(book_name, top_n=5):

    if book_name not in item_similarity_df.columns:
        return "Book not found."

    similar_books = item_similarity_df[book_name] \
                        .sort_values(ascending=False)[1:top_n+1]

    return similar_books

recommend_item_based(user_item_matrix.columns[0])

from sklearn.model_selection import train_test_split

# Assuming final_filtered is your cleaned dataset
train_data, test_data = train_test_split(
    final_df,
    test_size=0.2,
    random_state=42
)

print("Train Shape:", train_data.shape)
print("Test Shape:", test_data.shape)

## user_item matrix on train data
train_pivot = train_data.pivot_table(
    index='User-ID',
    columns='Book-Title',
    values='Book-Rating'
).fillna(0)

print(train_pivot.shape)

user_similarity = cosine_similarity(train_pivot)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=train_pivot.index,
    columns=train_pivot.index
)

item_similarity = cosine_similarity(train_pivot.T)

item_similarity_df = pd.DataFrame(
    item_similarity,
    index=train_pivot.columns,
    columns=train_pivot.columns
)

def recommend_user_based(user_id, top_n=5):

    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:21]

    similar_users_ratings = train_pivot.loc[similar_users.index]

    weighted_scores = similar_users_ratings.T.dot(similar_users)

    # Remove already rated books
    user_rated = train_pivot.loc[user_id]
    unrated_books = user_rated[user_rated == 0].index

    recommendations = weighted_scores.loc[unrated_books]

    return recommendations.sort_values(ascending=False).head(top_n)

def recommend_item_based(user_id, top_n=5):

    user_ratings = train_pivot.loc[user_id]
    rated_books = user_ratings[user_ratings > 0]

    scores = pd.Series(dtype=float)

    for book in rated_books.index:
        similar_items = item_similarity_df[book]
        scores = scores.add(similar_items * rated_books[book], fill_value=0)

    # Remove already rated
    scores = scores.drop(rated_books.index)

    return scores.sort_values(ascending=False).head(top_n)

def precision_at_k(model_func, k=5):

    precision_list = []

    test_users = test_data['User-ID'].unique()

    for user in test_users:

        if user not in train_pivot.index:
            continue

        actual_books = test_data[test_data['User-ID'] == user]['Book-Title'].tolist()

        if len(actual_books) == 0:
            continue

        recommended_books = model_func(user, top_n=k).index.tolist()

        relevant = set(actual_books)
        recommended = set(recommended_books)

        true_positive = len(relevant & recommended)

        precision = true_positive / k

        precision_list.append(precision)

    return sum(precision_list) / len(precision_list)

user_precision = precision_at_k(recommend_user_based, k=5)
item_precision = precision_at_k(recommend_item_based, k=5)

print("User-Based Precision@5:", user_precision)
print("Item-Based Precision@5:", item_precision)

# Your obtained results
user_precision = 0.07957559681697612
item_precision = 0.1103448275862069

# Create comparison table
comparison_df = pd.DataFrame({
    "Model": ["User-Based CF", "Item-Based CF"],
    "Precision@5": [user_precision, item_precision]
})

print(comparison_df)

plt.figure()
plt.bar(comparison_df["Model"], comparison_df["Precision@5"])
plt.xlabel("Model")
plt.ylabel("Precision@5")
plt.title("Model Performance Comparison (Precision@5)")
plt.xticks(rotation=20)
plt.show()

def recall_at_k(model_func, k=5):

    recall_list = []

    test_users = test_data['User-ID'].unique()

    for user in test_users:

        # Skip cold start users
        if user not in train_pivot.index:
            continue

        # Actual books from test set
        actual_books = test_data[test_data['User-ID'] == user]['Book-Title'].tolist()

        if len(actual_books) == 0:
            continue

        # Recommended books
        recommended_books = model_func(user, top_n=k).index.tolist()

        relevant = set(actual_books)
        recommended = set(recommended_books)

        true_positive = len(relevant & recommended)

        recall = true_positive / len(relevant)

        recall_list.append(recall)

    return sum(recall_list) / len(recall_list)

user_recall = recall_at_k(recommend_user_based, k=5)
item_recall = recall_at_k(recommend_item_based, k=5)

print("User-Based Recall@5:", user_recall)
print("Item-Based Recall@5:", item_recall)

comparison_df = pd.DataFrame({
    "Model": ["User-Based CF", "Item-Based CF"],
    "Precision@5": [user_precision, item_precision],
    "Recall@5": [user_recall, item_recall]
})

print(comparison_df)

plt.figure()
plt.bar(comparison_df["Model"], comparison_df["Recall@5"])
plt.xlabel("Model")
plt.ylabel("Recall@5")
plt.title("Recall@5 Comparison")
plt.xticks(rotation=20)
plt.show()

"""**Content-Based**"""

# Select required columns
content_data = final_df[['Book-Title', 'Book-Author', 'Publisher']].drop_duplicates()

# Fill missing values
content_data = content_data.fillna('')

content_data = content_data.reset_index(drop=True)

# Combine features
content_data['combined_features'] = (
    content_data['Book-Title'] + " " +
    content_data['Book-Author'] + " " +
    content_data['Publisher']
)

content_data.head()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(content_data['combined_features'])

print(tfidf_matrix.shape)

from sklearn.metrics.pairwise import cosine_similarity

content_similarity = cosine_similarity(tfidf_matrix)

print(content_similarity.shape)

def recommend_content_based(book_title, top_n=5):

    if book_title not in content_data['Book-Title'].values:
        return "Book not found"

    index = content_data[content_data['Book-Title'] == book_title].index[0]

    similarity_scores = list(enumerate(content_similarity[index]))

    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    similarity_scores = similarity_scores[1:top_n+1]

    ## extracts only index numbers
    book_indices = [i[0] for i in similarity_scores]

    return content_data['Book-Title'].iloc[book_indices]

recommend_content_based("The Da Vinci Code", top_n=5)

"""**Content_based Evaluation**"""

def evaluate_content_based(k=5):

    precision_list = []
    recall_list = []

    test_users = test_data['User-ID'].unique()

    for user in test_users:

        # Books user liked in train
        train_books = train_data[train_data['User-ID'] == user]['Book-Title'].tolist()
        test_books = test_data[test_data['User-ID'] == user]['Book-Title'].tolist()

        if len(train_books) == 0 or len(test_books) == 0:
            continue

        # Take one book from train
        base_book = train_books[0]

        if base_book not in content_data['Book-Title'].values:
            continue

        recommended_books = recommend_content_based(base_book, top_n=k)

        relevant = set(test_books)
        recommended = set(recommended_books)

        true_positive = len(relevant & recommended)

        precision = true_positive / k
        recall = true_positive / len(relevant)

        precision_list.append(precision)
        recall_list.append(recall)

    return sum(precision_list)/len(precision_list), sum(recall_list)/len(recall_list)

content_precision, content_recall = evaluate_content_based(k=5)

print("Content-Based Precision@5:", content_precision)
print("Content-Based Recall@5:", content_recall)

"""**Hybrid-Based**"""

def recommend_item_based_scores(user_id):

    user_ratings = train_pivot.loc[user_id]
    rated_books = user_ratings[user_ratings > 0]

    scores = pd.Series(dtype=float)

    for book in rated_books.index:
        if book in item_similarity_df.columns:
            similar_items = item_similarity_df[book]
            scores = scores.add(similar_items * rated_books[book], fill_value=0)

    ## drop already rated books
    scores = scores.drop(rated_books.index, errors='ignore')

    return scores

def get_content_scores(base_book):

    if base_book not in content_data['Book-Title'].values:
        return pd.Series(dtype=float)

    index = content_data[content_data['Book-Title'] == base_book].index[0]

    similarity_scores = pd.Series(
        content_similarity[index],
        index=content_data['Book-Title']
    )

    similarity_scores = similarity_scores.drop(base_book, errors='ignore')

    return similarity_scores

from sklearn.preprocessing import MinMaxScaler

def recommend_hybrid(user_id, alpha=0.85, top_n=5):

    if user_id not in train_pivot.index:
        return []

    # CF scores
    cf_scores = recommend_item_based_scores(user_id)

    # Base book for content
    user_books = train_data[train_data['User-ID'] == user_id]['Book-Title'].tolist()

    if len(user_books) == 0:
        return []

    base_book = user_books[0]
    content_scores = get_content_scores(base_book)

    # Combine only common books
    common_books = cf_scores.index.intersection(content_scores.index)

    if len(common_books) == 0:
        return cf_scores.sort_values(ascending=False).head(top_n).index.tolist()

    cf_scores = cf_scores.loc[common_books]
    content_scores = content_scores.loc[common_books]

    # Normalize
    scaler = MinMaxScaler()

    cf_norm = pd.Series(
        scaler.fit_transform(cf_scores.values.reshape(-1,1)).flatten(),
        index=cf_scores.index
    )

    content_norm = pd.Series(
        scaler.fit_transform(content_scores.values.reshape(-1,1)).flatten(),
        index=content_scores.index
    )

    hybrid_scores = alpha * cf_norm + (1 - alpha) * content_norm

    return hybrid_scores.sort_values(ascending=False).head(top_n).index.tolist()

recommend_hybrid(user_id=254, alpha=0.7, top_n=5)

## Evaluate Hybrid Model
def evaluate_hybrid(k=5):

    precision_list = []
    recall_list = []

    test_users = test_data['User-ID'].unique()

    for user in test_users:

        if user not in train_pivot.index:
            continue

        test_books = test_data[test_data['User-ID'] == user]['Book-Title'].tolist()

        if len(test_books) == 0:
            continue

        recommended_books = recommend_hybrid(user, alpha=0.7, top_n=k)

        relevant = set(test_books)
        recommended = set(recommended_books)

        true_positive = len(relevant & recommended)

        precision = true_positive / k
        recall = true_positive / len(relevant)

        precision_list.append(precision)
        recall_list.append(recall)

    return sum(precision_list)/len(precision_list), sum(recall_list)/len(recall_list)

hybrid_precision, hybrid_recall = evaluate_hybrid(k=5)

print("Hybrid Precision@5:", hybrid_precision)
print("Hybrid Recall@5:", hybrid_recall)

"""The hybrid model did not outperform Item-Based CF because the content-based component had weaker predictive power due to limited textual features (title, author, publisher). When combined, it diluted the stronger collaborative signal."""

# Final Model Evaluation Values

user_precision = 0.0713
user_recall = 0.2007

item_precision = 0.0947
item_recall = 0.2654

content_precision = 0.0425
content_recall = 0.1234

hybrid_precision = 0.0654
hybrid_recall = 0.1878

## finalcomparison table

results = pd.DataFrame({
    'Model': [
        'Content-Based',
        'User-Based CF',
        'Item-Based CF',
        'Hybrid'
    ],
    'Precision@5': [
        content_precision,
        user_precision,
        item_precision,
        hybrid_precision
    ],
    'Recall@5': [
        content_recall,
        user_recall,
        item_recall,
        hybrid_recall
    ]
})

results

# Calculate F1 Score
results['F1-Score@5'] = (
    2 * results['Precision@5'] * results['Recall@5'] /
    (results['Precision@5'] + results['Recall@5'])
)

results

best_model = results.loc[results['F1-Score@5'].idxmax()]

print("Best Performing Model:")
print(best_model)

import pickle

pickle.dump(train_pivot, open('pivot.pkl','wb'))
pickle.dump(user_similarity_df, open('similarity.pkl','wb'))  # or item_similarity_df (whichever you used)
pickle.dump(final_df, open('data.pkl','wb'))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

!pip install streamlit pyngrok

import streamlit as st
import pickle
import pandas as pd

# ----------------------------
# Load Saved Files
# ----------------------------
##pivot = pickle.load(open('pivot.pkl', 'rb'))
pivot = pickle.load(open('/content/pivot.pkl','rb'))
similarity = pickle.load(open('similarity.pkl', 'rb'))
data = pickle.load(open('data.pkl', 'rb'))

# ----------------------------
# Page Configuration
# ----------------------------
st.set_page_config(page_title="Book Recommendation System", layout="wide")

st.title("📚 Hybrid Book Recommendation System")
st.markdown("Collaborative Filtering + Content-Based Filtering")

# ----------------------------
# Recommendation Function
# ----------------------------
def recommend_books(user_id, top_n=5):

    if user_id not in pivot.index:
        return ["User not found in dataset"]

    # Get similarity scores for the user
    user_index = list(pivot.index).index(user_id)
    similarity_scores = list(enumerate(similarity[user_index]))

    # Sort users based on similarity
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    recommended_books = []

    # Skip first one (itself)
    for i in similarity_scores[1:]:
        similar_user = pivot.index[i[0]]

        # Get books rated by similar user
        books = data[data['User-ID'] == similar_user]['Book-Title'].values

        for book in books:
            if book not in recommended_books:
                recommended_books.append(book)

        if len(recommended_books) >= top_n:
            break

    return recommended_books[:top_n]


# ----------------------------
# UI Section
# ----------------------------

st.sidebar.header("User Input")

user_input = st.sidebar.text_input("Enter User ID")

top_n = st.sidebar.slider("Number of Recommendations", 1, 10, 5)

if st.sidebar.button("Recommend"):

    if user_input:
        try:
            user_id = int(user_input)

            recommendations = recommend_books(user_id, top_n)

            st.subheader("📖 Recommended Books")

            for book in recommendations:
                st.write("👉", book)

        except:
            st.error("Please enter a valid numeric User ID")
    else:
        st.warning("Please enter User ID")

!pip install streamlit pyngrok

from pyngrok import ngrok

!pkill -f streamlit
!pkill -f ngrok

!streamlit run app.py --server.port 8501 --server.headless true

!ps aux | grep streamlit

from pyngrok import ngrok
ngrok.set_auth_token("37EX2ZEgHa38J209fZSTDgSjhgu_5bb5a4thyjF3cXQFnovoQ")
public_url = ngrok.connect(8501)
public_url

!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# scikit-learn
# pickle-mixin

!ls

